---
title: "Dictionary 2000"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
urlcolor: blue
vignette: >
  %\VignetteIndexEntry{Dictionary 2000}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = identical(tolower(Sys.getenv("NOT_CRAN")), "true"),
  out.width = "100%"
)
```



# Population

<table border=0 cellpadding=0 cellspacing=0 width=911 style='border-collapse:
 collapse;table-layout:fixed;width:684pt'>
 <col width=116 style='mso-width-source:userset;mso-width-alt:4049;width:87pt'>
 <col width=280 style='mso-width-source:userset;mso-width-alt:9774;width:210pt'>
 <col width=515 style='mso-width-source:userset;mso-width-alt:17989;width:387pt'>
 <col width=442 style='mso-width-source:userset;mso-width-alt:15429;width:332pt'>
 <tr height=21 style='height:15.5pt'>
  <td colspan=3 height=21 class=xl69 width=911 style='height:15.5pt;width:684pt'>Variáveis
  do Registro de Pessoas</td>
 </tr>
 <tr height=27 style='mso-height-source:userset;height:20.5pt'>
  <td height=27 class=xl65 width=116 style='height:20.5pt;border-top:none;
  width:87pt'>Variavel</td>
  <td class=xl65 width=280 style='border-top:none;border-left:none;width:210pt'>Descrição</td>
  <td class=xl65 width=515 style='border-top:none;border-left:none;width:387pt'>Ctegorias</td>
 </tr>
 <tr height=546 style='height:409.5pt'>
  <td height=546 class=xl66 width=116 style='height:409.5pt;border-top:none;
  width:87pt'>V0102</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>UF</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>11-
  Rondônia<br>
    12- Acre<br>
    13- Amazonas<br>
    14- Roraima<br>
    15- Pará<br>
    16- Amapá<br>
    17 - Tocantins<br>
    21- Maranhão<br>
    22- Piauí<br>
    23- Ceará<br>
    24- Rio Grande do Norte<br>
    25- Paraíba<br>
    26- Pernambuco<br>
    27- Alagoas<br>
    28 - Sergipe<br>
    29- Bahia<br>
    31- Minas Gerais<br>
    32- Espírito Santo<br>
    33- Rio de Janeiro<br>
    35- São Paulo<br>
    41- Paraná<br>
    42- Santa Catarina<br>
    43- Rio Grande do Sul<br>
    50- Mato Grosso do Sul<br>
    51- Mato Grosso<br>
    52- Goiás<br>
    53- Distrito Federal</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V1002</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Mesorregião</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V1003</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Microrregião</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0103</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Município</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0104</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Distrito</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0105</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Subdistrito</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0300</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>controle</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0404</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>&gt;00
  (número de ordem da familia no domicilio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=103 style='height:77.5pt'>
  <td height=103 class=xl66 width=116 style='height:77.5pt;border-top:none;
  width:87pt'>V1001</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Região
  geográfica</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1-
  Região Norte<br>
    2- Região Nordeste<br>
    3- Região Sudeste<br>
    4- Região Sul<br>
    5- Região Centro-Oeste</td>
 </tr>
 <tr height=546 style='mso-height-source:userset;height:409.5pt'>
  <td height=546 class=xl66 width=116 style='height:409.5pt;border-top:none;
  width:87pt'>V1004</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Regiao
  metropolitana</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>00
  – Sem Área de Ponderação<br>
    01 – Belém<br>
    02 – Grande São Luís<br>
    03 – Fortaleza<br>
    04 – Natal<br>
    05 – Recife<br>
    06 – Maceió<br>
    07 – Salvador<br>
    08 – Belo Horizonte<br>
    09 – Colar Metropolitano da RM de Belo Horizonte<br>
    10 – Vale do Aço<br>
    11 – Colar Metropolitano da RM do Vale do Aço<br>
    12 – Grande Vitória<br>
    13 – Rio de Janeiro<br>
    14 – São Paulo<br>
    15 – Baixada Santista<br>
    16 – Campinas<br>
    17 – Curitiba<br>
    18 – Londrina<br>
    19 – Maringá<br>
    20 – Florianópolis<br>
    21 – Área de Expansão Metropolitana da RM de Florianópolis<br>
    22 – Núcleo Metropolitano da RM Vale do Itajaí<br>
    23 – Área de Expansão Metropolitana da RM Vale do Itajaí<br>
    24 – Norte/Nordeste Catarinense<br>
    25 – Área de Expansão Metropolitana da RM Norte/Nordeste Catarinense<br>
    26 – Porto Alegre<br>
    27 – Goiânia<br>
    28 – Distrito Federal e Entorno</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl66 width=116 style='height:30.0pt;border-top:none;
  width:87pt'>AREAP</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Area
  de ponderação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=165 style='height:124.0pt'>
  <td height=165 class=xl66 width=116 style='height:124.0pt;border-top:none;
  width:87pt'>V1005</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Situação
  do setor</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Área urbanizada de vila ou cidade<br>
    2 – Área não urbanizada de vila ou cidade<br>
    3 – Área urbanizada isolada<br>
    4 – Rural - extensão urbana<br>
    5 – Rural – povoado<br>
    6 – Rural – núcleo<br>
    7 – Rural - outros aglomerados<br>
    8 – Rural – exclusive os aglomerados rurais</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V1006</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Situação
  do Domicilio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Urbano<br>
    2 – Rural</td>
 </tr>
 <tr height=165 style='height:124.0pt'>
  <td height=165 class=xl66 width=116 style='height:124.0pt;border-top:none;
  width:87pt'>V1007</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Tipo
  de setor</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  – Não especial: Setor comum<br>
    1 – Aglomerado subnormal<br>
    2 – Quartel<br>
    3 – Alojamento<br>
    4 – Embarcação<br>
    5 – Aldeia indígena<br>
    6 – Penitenciária<br>
    7 – Asilo</td>
 </tr>
 <tr height=43 style='mso-height-source:userset;height:32.0pt'>
  <td height=43 class=xl66 width=116 style='height:32.0pt;border-top:none;
  width:87pt'>V0300</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Controle</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Identificação
  do domicílio</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0400</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Número
  de ordem da pessoa recenseada</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>MARCA</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Se
  a própria pessoa prestou as informações</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Se a própria pessoa prestou as informações<br>
    Branco – As informações foram prestadas por outra pessoa do domicílio</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0401</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Sexo</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Masculino<br>
    2 – Feminino</td>
 </tr>
 <tr height=248 style='height:186.0pt'>
  <td height=248 class=xl66 width=116 style='height:186.0pt;border-top:none;
  width:87pt'>V0402</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Relação
  com responsável pelo domicílio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Pessoa responsável<br>
    2 – Cônjuge, companheiro(a)<br>
    3 – Filho(a), enteado(a)<br>
    4 – Pai, mãe, sogro(a)<br>
    5 – Neto(a), bisneto(a)<br>
    6 – Irmão, irmã<br>
    7 – Outro parente<br>
    8 – Agregado(a)<br>
    9 – Pensionista<br>
    10 – Empregado(a) doméstico(a)<br>
    11 – Parente do empregado(a) doméstico(a)<br>
    12 – Individual em domicílio coletivo</td>
 </tr>
 <tr height=248 style='height:186.0pt'>
  <td height=248 class=xl66 width=116 style='height:186.0pt;border-top:none;
  width:87pt'>V0403</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Relação
  com responsável pela família</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Pessoa responsável<br>
    2 – Cônjuge, companheiro(a)<br>
    3 – Filho(a), enteado(a)<br>
    4 – Pai, mãe, sogro(a)<br>
    5 – Neto(a), bisneto(a)<br>
    6 – Irmão, irmã<br>
    7 – Outro parente<br>
    8 – Agregado(a)<br>
    9 – Pensionista<br>
    10 – Empregado(a) doméstico(a)<br>
    11 – Parente do empregado(a) doméstico(a)<br>
    12 – Individual em domicílio coletivo</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0404</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Número
  da família</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4752</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Idade
  calculada em anos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4754</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Idade
  calculada em meses - menos de 1 ano</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V4070</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Indicadora
  da forma de declaração da idade</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Idade calculada: aquela em que o informante declara o mês e o ano de
  nascimento;<br>
    2 – Idade presumida/declarada</td>
 </tr>
 <tr height=186 style='height:139.5pt'>
  <td height=186 class=xl66 width=116 style='height:139.5pt;border-top:none;
  width:87pt'>V0408</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Cor
  ou raça</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Branca: pessoa que se enquadrou como branca;<br>
    2 – Preta: pessoa que se enquadrou como preta;<br>
    3 – Amarela: pessoa que se enquadrou como amarela (de origem japonesa,
  chinesa, coreana; etc.);<br>
    4 – Parda: pessoa que se enquadrou como parda ou que se declarou mulata,
  mestiça, cabocla, cafuza, mameluca;<br>
    5 – Indígena: pessoa que se enquadrou como indígena ou se declarou como
  tal, vivendo em aldeamento ou fora deste;<br>
    9 – Ignorado</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4090</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da religião</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0410</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Problema
  mental permanente</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não<br>
    9 – Ignorado</td>
 </tr>
 <tr height=227 style='height:170.5pt'>
  <td height=227 class=xl66 width=116 style='height:170.5pt;border-top:none;
  width:87pt'>V0411</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Capacidade
  de enxergar</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Incapaz: Pessoa que se declarou totalmente cega.<br>
    2 – Grande dificuldade permanente: Pessoa que se declarou com grande
  dificuldade permanente para enxergar, mesmo com o uso de óculos ou lentes de
  contato.<br>
    3 – Alguma dificuldade permanente: Pessoa que se declarou com alguma
  dificuldade permanente para enxergar, mesmo com uso de óculos ou lentes de
  contato.<br>
    4 – Nenhuma dificuldade: Pessoa que se declarou sem nenhuma dificuldade
  permanente para enxergar, ainda que isto exija o uso de óculos ou lentes de
  contato.<br>
    9 – Ignorado</td>
 </tr>
 <tr height=165 style='height:124.0pt'>
  <td height=165 class=xl66 width=116 style='height:124.0pt;border-top:none;
  width:87pt'>V0412</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Capacidade
  de ouvir</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Incapaz: Pessoa que se declarou totalmente surda.<br>
    2 – Grande dificuldade permanente: Pessoa que se declarou com grande
  dificuldade permanente para ouvir, mesmo com o uso de aparelho
  auditivo.<br>
    3 – Alguma dificuldade permanente: Pessoa que se declarou com alguma
  dificuldade permanente para ouvir, mesmo com o uso de aparelho
  auditivo.<br>
    4 – Nenhuma dificuldade: Pessoa que se declarou sem nenhuma dificuldade
  para ouvir, ainda que isto exija o uso de aparelho auditivo.<br>
    9 – Ignorado</td>
 </tr>
 <tr height=269 style='height:201.5pt'>
  <td height=269 class=xl66 width=116 style='height:201.5pt;border-top:none;
  width:87pt'>V0413</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Capacidade
  de caminhar/subir escadas</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Incapaz: Pessoa que se declarou incapaz de caminhar ou subir escadas sem
  ajuda de outra pessoa, por deficiência motora.<br>
    2 – Grande dificuldade permanente: Pessoa que se declarou com grande
  dificuldade permanente de caminhar ou subir escadas sem ajuda de outra
  pessoa, mesmo com o uso de prótese ou aparelho auxiliar.<br>
    3 – Alguma dificuldade permanente: Pessoa que se declarou com alguma
  dificuldade permanente de caminhar ou subir escadas sem ajuda de outra
  pessoa, mesmo com o uso de prótese ou aparelho auxiliar.<br>
    4 – Nenhuma dificuldade: Pessoa que se declarou sem nenhuma dificuldade de
  caminhar ou subir escada sem ajuda de outra pessoa, ainda que isto exija o
  uso de prótese ou aparelho auxiliar. Considerar neste item as crianças que,
  por sua pouca idade, apresentam pouca ou nenhuma capacidade de
  caminhar.<br>
    9 – Ignorado</td>
 </tr>
 <tr height=227 style='height:170.5pt'>
  <td height=227 class=xl66 width=116 style='height:170.5pt;border-top:none;
  width:87pt'>V0414</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Deficiências</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Paralisia permanente total: Pessoa que se declarou tetraplégica ou
  quadriplégica, ou seja, possui paralisia dos quatro membros.<br>
    2 – Paralisia permanente das pernas: Pessoa que se declarou
  paraplégica.<br>
    3 – Paralisia permanente de um dos lados do corpo: Pessoa que se declarou
  hemiplégica.<br>
    4 – Falta de perna, braço, mão, pé ou dedo polegar: Pessoa que se declarou
  com falta de perna, braço, mão, pé ou dedo polegar. Também foi considerada
  neste caso a pessoa que declarou perda de parte de um braço ou perna.<br>
    5 – Nenhuma das enumeradas: Pessoa que não possui nenhuma das deficiências
  físicas enumeradas.<br>
    9 – Ignorado</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0415</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Sempre
  morou neste município</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0416</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Tempo
  de moradia neste Município</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0417</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Nasceu
  neste Município</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0418</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Nasceu
  nesta UF</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0419</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Nacionalidade</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  –Brasileiro nato: pessoa nascida no Brasil ou nascida em país estrangeiro que
  foi registrada como brasileiro, segundo as Leis do Brasil;<br>
    2 – Naturalizado brasileiro: pessoa que nasceu em país estrangeiro e obteve
  a nacionalidade brasileira por meio de título de naturalização ou valendo-se
  de disposição da legislação brasileira;<br>
    3 – Estrangeiro: pessoa que nasceu fora do Brasil ou para aquela que nasceu
  no Brasil e foi registrada em Representação Estrangeira e não se naturalizou
  brasileira.<br>
    Branco – para os não migrantes e os naturais da Unidade da Federação onde
  foi realizado o Censo 2000.</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0420</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Ano
  que fixou residência no Brasil</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  – para os não migrantes e os brasileiros natos</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4210</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País de nascimento</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco<font
  class="font8"> – para os não migrantes e os naturais da Unidade da Federação
  onde foi realizado o Censo 2000.</font></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0422</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Tempo
  de moradia na UF</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  <font class="font8">– para os não migrantes.</font></td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0430</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País de residência anterior</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  – <font class="font8">para os não migrantes e os que moram na Unidade da
  Federação há 10 anos ou mais.</font></td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=116 style='height:108.5pt;border-top:none;
  width:87pt'>V0424</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Residência
  em 31 de julho de 1995</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Neste Município, na Zona Urbana<br>
    2 – Neste Município, na Zona Rural<br>
    3 – Em outro Município, na Zona Urbana<br>
    4 – Em outro Município, na Zona Rural<br>
    5 – Em outro País<br>
    6 – Não era nascido<br>
    Branco – para os não migrantes</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V4250</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  do município de residência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  <font class="font8">– para os não migrantes, os moradores no município onde
  foi realizado o Censo 2000, os moradores em outro País e aos não nascidos em
  31/07/1995.</font></td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4260</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País de residência em 31/07/1995</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  –<font class="font8"> para os não migrantes, os moradores no município onde
  foi realizado o Censo 2000 e os não nascidos em 31/07/1995.</font></td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V4276</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  do município e Unidade da Federação ou País Estrangeiro que trabalha ou
  estuda</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0428</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Sabe
  ler e escrever</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sabe ler e escrever<br>
    2 – Não sabe</td>
 </tr>
 <tr height=83 style='height:62.0pt'>
  <td height=83 class=xl66 width=116 style='height:62.0pt;border-top:none;
  width:87pt'>V0429</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Freqüenta
  escola ou creche</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim, rede particular<br>
    2 – Sim, rede pública<br>
    3 – Não, já freqüentou<br>
    4 – Nunca freqüentou</td>
 </tr>
 <tr height=289 style='height:217.0pt'>
  <td height=289 class=xl66 width=116 style='height:217.0pt;border-top:none;
  width:87pt'>V0430</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Curso
  que freqüenta</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Creche<br>
    2 – Pré-escolar<br>
    3 – Classe de alfabetização<br>
    4 – Alfabetização de adultos<br>
    5 – Ensino fundamental ou 1º grau – regular seriado<br>
    6 – Ensino fundamental ou 1º grau – regular não-seriado<br>
    7 – Supletivo (ensino fundamental ou 1º grau)<br>
    8 – Ensino médio ou 2º grau – regular seriado<br>
    9 – Ensino médio ou 2º grau – regular não-seriado<br>
    10 – Supletivo (ensino médio ou 2º grau)<br>
    11 – Pré-vestibular<br>
    12 – Superior – graduação<br>
    13 – Mestrado ou doutorado<br>
    Branco – para os não estudantes</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0431</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Série
  que freqüenta</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Primeira Série<br>
    2 – Segunda Série<br>
    3 – Terceira Série<br>
    4 – Quarta Série<br>
    5 – Quinta Série<br>
    6 – Sexta Série<br>
    7 – Sétima Série<br>
    8 – Oitava Série<br>
    9 – Curso não seriado<br>
    Branco – para os não estudantes</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0432</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Curso
  mais elevado que freqüentou, concluindo pelo menos uma série</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Alfabetização de adultos<br>
    2 – Antigo primário<br>
    3 – Antigo ginásio<br>
    4 – Antigo clássico, científico, etc.<br>
    5 – Ensino fundamental ou 1º grau<br>
    6 – Ensino médio ou 2º Grau<br>
    7 –Superior – graduação<br>
    8 – Mestrado ou doutorado<br>
    9 – Nenhum<br>
    Branco – para os estudantes</td>
 </tr>
 <tr height=227 style='height:170.5pt'>
  <td height=227 class=xl66 width=116 style='height:170.5pt;border-top:none;
  width:87pt'>V0433</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Última
  série concluída com aprovação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Primeira Série<br>
    2 – Segunda Série<br>
    3 – Terceira Série<br>
    4 – Quarta Série<br>
    5 – Quinta Série<br>
    6 – Sexta Série<br>
    7 – Sétima Série<br>
    8 – Oitava Série<br>
    9 – Curso não seriado<br>
    10 – Nenhuma<br>
    Branco – para os estudantes</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0434</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Concluiu
  o curso no qual estudou</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não<br>
    Branco – para os estudantes</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0435</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  do curso mais elevado concluído</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=413 style='height:310.0pt'>
  <td height=413 class=xl66 width=116 style='height:310.0pt;border-top:none;
  width:87pt'>V4300</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Anos
  de estudo</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>00
  - Sem instrução ou menos de 1 ano<br>
    01 - 1 ano<br>
    02 - 2 anos<br>
    03- 3 anos<br>
    04 - 4 anos<br>
    05 - 5 anos<br>
    06 - 6 anos<br>
    07 - 7 anos<br>
    08 - 8 anos<br>
    09- 9 anos<br>
    10 - 10 anos<br>
    11 - 11 anos<br>
    12 - 12 anos<br>
    13 - 13 anos<br>
    14 - 14 anos<br>
    15 - 15 anos<br>
    16 - 16 anos<br>
    17 - 17 anos ou mais<br>
    20 - Não determinado<br>
    30 - Alfabetização de adultos</td>
 </tr>
 <tr height=83 style='height:62.0pt'>
  <td height=83 class=xl66 width=116 style='height:62.0pt;border-top:none;
  width:87pt'>V0436</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Vive
  em companhia de cônjuge ou companheiro(a)</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não, mas viveu<br>
    3 - Nunca viveu<br>
    Branco - para as pessoas com menos de 10 anos de idade</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V0437</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Natureza
  da última união</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Casamento civil e religioso<br>
    2 – Só casamento civil<br>
    3 - Só casamento religioso<br>
    4 - União consensual<br>
    5 - Nunca viveu<br>
    Branco - para as pessoas com menos de 10 anos de idade</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V0438</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Estado
  civil</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Casado(a)<br>
    2 - Desquitado(a) ou separado(a) judicialmente<br>
    3 - Divorciado(a)<br>
    4 - Viúvo(a)<br>
    5 – Solteiro(a<br>
    Branco – para as pessoas com menos de 10 anos de idade</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0439</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Na semana de 23 a 29/7/2000 trabalhou
  remunerado</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0440</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Na
  semana, tinha trabalho mas estava afastado</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade</td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=116 style='height:108.5pt;border-top:none;
  width:87pt'>V0441</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Na
  semana, ajudou sem remuneração, no trabalho exercido por pessoa moradora do
  domicílio, ou como aprendiz ou estagiário</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que exerceram algum trabalho remunerado na totalidade
  ou em parte da semana de referência do Censo ou tinham algum trabalho remunerado
  na semana de referência do qual estava temporariamente afastado.</td>
 </tr>
 <tr height=186 style='height:139.5pt'>
  <td height=186 class=xl66 width=116 style='height:139.5pt;border-top:none;
  width:87pt'>V0442</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Na
  semana, ajudou sem remuneração, no trabalho exercido por pessoa moradora do
  domicílio em atividade de cultivo, extração vegetal</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que exerceram algum trabalho remunerado na totalidade
  ou em parte da semana de referência do Censo ou tinham algum trabalho remunerado
  na semana de referência do qual estavam temporariamente afastado ou ajudaram
  sem remuneração pessoa conta-própria ou empregadora moradora no domicílio, ou
  como aprendiz ou estagiário.</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0443</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Na
  semana, trabalhou no cultivo, etc. para alimentação de pessoas moradoras no
  domicílio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que exerceram algum trabalho remunerado na totalidade
  ou em parte da semana de referência do Censo ou tinham algum trabalho remunerado
  na semana de referência do qual estavam temporariamente afastado ou ajudaram
  sem remuneração pessoa conta-própria ou empregadora moradora no domicílio, ou
  como aprendiz ou estagiário ou ajudaram sem remuneração pessoa moradora no
  domicílio empregada em atividade de produção de bens primários.</td>
 </tr>
 <tr height=83 style='height:62.0pt'>
  <td height=83 class=xl66 width=116 style='height:62.0pt;border-top:none;
  width:87pt'>V0444</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Quantos
  trabalhos tinha na semana de 23 a 29 de julho de 2000</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Um<br>
    2 - Dois ou mais<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4452<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  novo da ocupação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para pessoa de menos de 10 anos de idade ou pessoa de 10 ou mais anos de
  idade que não tinha trabalho na semana de referência.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4462</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  novo da atividade</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para pessoa de menos de 10 anos de idade ou pessoa de 10 ou mais anos de
  idade que não tinha trabalho na semana de referência.</td>
 </tr>
 <tr height=227 style='height:170.5pt'>
  <td height=227 class=xl66 width=116 style='height:170.5pt;border-top:none;
  width:87pt'>V0447</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Nesse
  trabalho era...</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Trabalhador doméstico com carteira de trabalho assinada<br>
    2 - Trabalhador doméstico sem carteira de trabalho assinada<br>
    3 - Empregado com carteira de trabalho assinada<br>
    4 - Empregado sem carteira de trabalho assinada<br>
    5 - Empregador<br>
    6 - Conta-própria<br>
    7 - Aprendiz ou estagiário sem remuneração<br>
    8 - Não remunerado em ajuda a membro do domicílio<br>
    9 - Trabalhador na produção para o próprio consumo<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência.</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V0448</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Era
  empregado pelo RJFP ou como militar</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência do
  Censo e as que não tenham sido classificadas como empregado sem carteira de
  trabalho assinada no trabalho principal, posição na ocupação.</td>
 </tr>
 <tr height=103 style='height:77.5pt'>
  <td height=103 class=xl66 width=116 style='height:77.5pt;border-top:none;
  width:87pt'>V0449</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Quantos
  empregados trabalhavam nessa firma</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Um<br>
    2 - Dois<br>
    3 - De 3 a 5 empregados<br>
    4 - De 6 a 10 empregados<br>
    5 - 11 ou mais empregados</td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=116 style='height:108.5pt;border-top:none;
  width:87pt'>V0450</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Era
  contribuinte de instituto de previdenciária oficial</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência do
  Censo e as que tenham sido classificadas como aprendiz ou estagiário sem
  remuneração, exerciam trabalho não remunerado em ajuda a membro do domicílio,
  ou trabalhavam para o próprio consumo.</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V4511</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Não
  tem rendimento no trabalho principal</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  - Não Tem<br>
    1 - Somente em benefícios<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência do
  Censo e as que tinham rendimento do trabalho principal remunerado na semana
  de referência do Censo.</td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=116 style='height:108.5pt;border-top:none;
  width:87pt'>V4512</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  bruto no trabalho principal</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade e pessoa com 10 anos ou mais de
  idade que não tinha trabalho, a pessoa que tinha trabalho principal
  remunerado recebendo somente em benefícios e a pessoa que tinha trabalho
  principal não remunerado na semana de referência do Censo.<br>
    NOTA: Se o rendimento mensal do trabalho principal ultrapassou o valor de
  R$ 999.998,00 (novecentos e noventa e nove mil, novecentos e noventa e oito
  reais), o valor registrado no campo será 999998</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V4513</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos no trabalho principal</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade e a pessoa com 10 anos ou mais
  de idade que não tinha trabalho na semana de referência do Censo.<br>
    NOTA: Se o total dos rendimentos do trabalho principal ultrapassou o valor
  de R$ 999.998,00 (novecentos e noventa e nove mil, novecentos e noventa e
  oito reais), o valor registrado no campo será 999998.</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V4514</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos no trabalho principal, em salários mínimos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade e a pessoa com 10 anos ou mais
  de idade que não tinha trabalho na semana de referência do Censo.</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V4521</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Não
  tem rendimento nos demais trabalhos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  - Não Tem<br>
    1 - Somente em benefícios<br>
    Branco - para as pessoas com menos de 10 anos de idade e pessoas com 10
  anos ou mais de idade que não tinham trabalho na semana de referência do
  Censo e as que tinham rendimento de outro trabalho remunerado na semana de
  referência do Censo.</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4522</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  bruto nos demais trabalhos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4523</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos nos demais trabalhos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4524</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos nos demais trabalhos, em salários mínimos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4525</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos em todos os trabalhos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4526</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos em todos os trabalhos, em salários mínimos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0453<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Horas
  trabalhadas por semana no trabalho principal</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0454</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Horas
  trabalhadas nos demais trabalhos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4534</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de horas trabalhadas</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=83 style='height:62.0pt'>
  <td height=83 class=xl66 width=116 style='height:62.0pt;border-top:none;
  width:87pt'>V0455</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Providência
  para conseguir trabalho</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para a pessoa com menos de 10 anos de idade e a pessoa com 10 anos
  ou mais de idade que tinha trabalho na semana de referência do Censo.</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0456</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Em
  julho de 2000, era aposentado de instituto de previdência oficial</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  - Sim<br>
    2 - Não<br>
    Branco - para as pessoas com menos de 10 anos de idade.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4573</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  de aposentadoria ou pensão</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4583</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  de aluguel</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4593</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  de pensão alimentícia, mesada, doação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4603</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  renda mínima, bolsa escola, seguro desemprego</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4613</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Outros
  rendimentos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4614</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4615</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Total
  de rendimentos, em salários mínimos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para a pessoa com menos de 10 anos de idade na data de referência do Censo.</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4620<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Total de filhos nascidos vivos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0463<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Total de filhos nascidos vivos que estavam
  vivos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4654<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Idade calculada do último nascido vivo</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4670<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Total de filhos nascidos mortos, número</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4690<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Total de filhos tidos, número</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4621<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Filhos nascidos vivos: Homens</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4622<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Filhos nascidos vivos: Mulheres</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4631<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Filhos que estavam vivos: Homens</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4632<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'><span
  style='mso-spacerun:yes'> </span>Filhos que estavam vivos: Mulheres</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=103 style='height:77.5pt'>
  <td height=103 class=xl66 width=116 style='height:77.5pt;border-top:none;
  width:87pt'>V0464</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Sexo
  do último filho nascido vivo</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Masculino<br>
    2 - Feminino<br>
    Branco - para os homens, as mulheres com menos de 10 anos de idade e as
  mulheres com 10 anos de idade ou mais que não tiveram filhos vivos até a data
  de referência do Censo.</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4671</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Filhos
  nascidos mortos:homens</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4672</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Filhos
  nascidos mortos:mulheres</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4354<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  do curso mais elevado concluído</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4219<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País de nascimento (ONU)</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Branco
  - para os não migrantes e os naturais da Unidade da Federação onde foi
  realizado o Censo 2000.</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4239</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País (ONU) de residência anterior</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4269</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  da UF ou País (ONU) de residência em 31/07/1995</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V4279</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  do País Estrangeiro (ONU) que trabalha ou estuda</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4451</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  antigo da ocupação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V4461</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Código
  antigo da atividade</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>P001</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Peso</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>ESTR</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Estrato
  de imputação de renda</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>ESTRP</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Estrato
  de imputação de renda parcial</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=116 style='width:87pt'></td>
  <td width=280 style='width:210pt'></td>
  <td width=515 style='width:387pt'></td>
 </tr>
 <![endif]>
</table>



# Households


<table border=0 cellpadding=0 cellspacing=0 width=911 style='border-collapse:
 collapse;table-layout:fixed;width:684pt'>
 <col width=116 style='mso-width-source:userset;mso-width-alt:4049;width:87pt'>
 <col width=280 style='mso-width-source:userset;mso-width-alt:9774;width:210pt'>
 <col width=515 style='mso-width-source:userset;mso-width-alt:17989;width:387pt'>
 <col width=442 style='mso-width-source:userset;mso-width-alt:15429;width:332pt'>
 <tr height=21 style='height:15.5pt'>
  <td colspan=3 height=21 class=xl69 width=911 style='height:15.5pt;width:684pt'>Variáveis
  do Registro de Domicilios</td>
 </tr>
 <tr height=27 style='mso-height-source:userset;height:20.5pt'>
  <td height=27 class=xl65 width=116 style='height:20.5pt;border-top:none;
  width:87pt'>Variavel</td>
  <td class=xl65 width=280 style='border-top:none;border-left:none;width:210pt'>Descrição</td>
  <td class=xl65 width=515 style='border-top:none;border-left:none;width:387pt'>Ctegorias</td>
 </tr>
 <tr height=546 style='height:409.5pt'>
  <td height=546 class=xl66 width=116 style='height:409.5pt;border-top:none;
  width:87pt'>V0102</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>UF</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>11-
  Rondônia<br>
    12- Acre<br>
    13- Amazonas<br>
    14- Roraima<br>
    15- Pará<br>
    16- Amapá<br>
    17 - Tocantins<br>
    21- Maranhão<br>
    22- Piauí<br>
    23- Ceará<br>
    24- Rio Grande do Norte<br>
    25- Paraíba<br>
    26- Pernambuco<br>
    27- Alagoas<br>
    28 - Sergipe<br>
    29- Bahia<br>
    31- Minas Gerais<br>
    32- Espírito Santo<br>
    33- Rio de Janeiro<br>
    35- São Paulo<br>
    41- Paraná<br>
    42- Santa Catarina<br>
    43- Rio Grande do Sul<br>
    50- Mato Grosso do Sul<br>
    51- Mato Grosso<br>
    52- Goiás<br>
    53- Distrito Federal</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V1002</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Mesorregião</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V1003</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Microrregião</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0103</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Município</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0104</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Distrito</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0105</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Subdistrito</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0300</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>controle</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0404</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>&gt;00
  (número de ordem da familia no domicilio</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=103 style='height:77.5pt'>
  <td height=103 class=xl66 width=116 style='height:77.5pt;border-top:none;
  width:87pt'>V1001</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Região
  geográfica</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1-
  Região Norte<br>
    2- Região Nordeste<br>
    3- Região Sudeste<br>
    4- Região Sul<br>
    5- Região Centro-Oeste</td>
 </tr>
 <tr height=546 style='mso-height-source:userset;height:409.5pt'>
  <td height=546 class=xl66 width=116 style='height:409.5pt;border-top:none;
  width:87pt'>V1004</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Regiao
  metropolitana</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>00
  – Sem Área de Ponderação<br>
    01 – Belém<br>
    02 – Grande São Luís<br>
    03 – Fortaleza<br>
    04 – Natal<br>
    05 – Recife<br>
    06 – Maceió<br>
    07 – Salvador<br>
    08 – Belo Horizonte<br>
    09 – Colar Metropolitano da RM de Belo Horizonte<br>
    10 – Vale do Aço<br>
    11 – Colar Metropolitano da RM do Vale do Aço<br>
    12 – Grande Vitória<br>
    13 – Rio de Janeiro<br>
    14 – São Paulo<br>
    15 – Baixada Santista<br>
    16 – Campinas<br>
    17 – Curitiba<br>
    18 – Londrina<br>
    19 – Maringá<br>
    20 – Florianópolis<br>
    21 – Área de Expansão Metropolitana da RM de Florianópolis<br>
    22 – Núcleo Metropolitano da RM Vale do Itajaí<br>
    23 – Área de Expansão Metropolitana da RM Vale do Itajaí<br>
    24 – Norte/Nordeste Catarinense<br>
    25 – Área de Expansão Metropolitana da RM Norte/Nordeste Catarinense<br>
    26 – Porto Alegre<br>
    27 – Goiânia<br>
    28 – Distrito Federal e Entorno</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl66 width=116 style='height:30.0pt;border-top:none;
  width:87pt'>AREAP</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Area
  de ponderação</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=165 style='height:124.0pt'>
  <td height=165 class=xl66 width=116 style='height:124.0pt;border-top:none;
  width:87pt'>V1005</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Situação
  do setor</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Área urbanizada de vila ou cidade<br>
    2 – Área não urbanizada de vila ou cidade<br>
    3 – Área urbanizada isolada<br>
    4 – Rural - extensão urbana<br>
    5 – Rural – povoado<br>
    6 – Rural – núcleo<br>
    7 – Rural - outros aglomerados<br>
    8 – Rural – exclusive os aglomerados rurais</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V1006</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Situação
  do Domicilio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Urbano<br>
    2 – Rural</td>
 </tr>
 <tr height=165 style='height:124.0pt'>
  <td height=165 class=xl66 width=116 style='height:124.0pt;border-top:none;
  width:87pt'>V1007</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Tipo
  de setor</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  – Não especial: Setor comum<br>
    1 – Aglomerado subnormal<br>
    2 – Quartel<br>
    3 – Alojamento<br>
    4 – Embarcação<br>
    5 – Aldeia indígena<br>
    6 – Penitenciária<br>
    7 – Asilo</td>
 </tr>
 <tr height=43 style='mso-height-source:userset;height:32.0pt'>
  <td height=43 class=xl66 width=116 style='height:32.0pt;border-top:none;
  width:87pt'>V0300</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Controle</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Identificação
  do domicílio</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0400</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Domicílio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>Identificação
  do registro de domicílio (V0400 = 00)</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0110</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Número
  de moradores homens</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0111</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Número
  de moradores mulheres</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0201</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Espécie
  de domicílio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Particular permanente<br>
    2 – Particular improvisado<br>
    3 – Coletivo</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0202</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Tipo
  de domicilio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Casa<br>
    2 – Apartamento<br>
    3 – Cômodo</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0203</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de comodos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0204</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de comodos como dormitorio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V0205</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Condição
  de ocupação do domicílio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Próprio, já pago<br>
    2 – Próprio, ainda pagando<br>
    3 – Alugado:<br>
    4 – Cedido por empregador<br>
    5 – Cedido de outra forma<br>
    6 – Outra Condição</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0206</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Condição
  de ocupação do terreno</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Próprio<br>
    2 – Cedido<br>
    3 – Outra condição</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0207</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Abastecimento
  de água, origem</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Rede geral<br>
    2 – Poço ou nascente<br>
    3 – Outra</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V0208</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Abastecimento
  de água, canalização</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Canalizada em pelo menos um cômodo<br>
    2 – Canalizada só na propriedade ou terreno<br>
    3 – Não canalizada</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0209</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de banheiros</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0210</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Existencia
  de sanitário</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=124 style='height:93.0pt'>
  <td height=124 class=xl66 width=116 style='height:93.0pt;border-top:none;
  width:87pt'>V0211</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Esgotamento
  sanitário, forma</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Rede geral<br>
    2 – Fossa séptica<br>
    3 – Fossa rudimentar<br>
    4 – Vala<br>
    5 – Rio, lago ou mar<br>
    6 – Outro escoadouro</td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=116 style='height:108.5pt;border-top:none;
  width:87pt'>V0212</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Lixo,
  destino</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Coletado por serviço de limpeza<br>
    2 – Caçamba do serviço de limpeza<br>
    3 – Queimado<br>
    4 – Enterrado<br>
    5 – Terreno baldio ou logradouro<br>
    6 – Jogado em rio, lago ou mar<br>
    7 – Outro destino</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0213</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Iluminação
  elétrica, existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0214</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rádio,
  existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0215</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Geladeira
  ou freezer, existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0216</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Videocassete,
  existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0217</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Máquina
  de lavar roupa, existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0218</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Forno
  de microondas, existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0219</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Linha
  telefônica instalada, existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=116 style='height:31.0pt;border-top:none;
  width:87pt'>V0220</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Microcomputador,
  existência</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V0221</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de televisores</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0222</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de automoveis para uso particular</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  – Não tem<br>
    1 – 1 automóvel<br>
    2 – 2 automóveis<br>
    3 – 3 automóveis<br>
    4 – 4 automóveis<br>
    5 – 5 automóveis<br>
    6 – 6 automóveis<br>
    7 – 7 automóveis<br>
    8 – 8 automóveis<br>
    9 – 9 ou mais automóveis</td>
 </tr>
 <tr height=207 style='height:155.0pt'>
  <td height=207 class=xl66 width=116 style='height:155.0pt;border-top:none;
  width:87pt'>V0223</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de aparelhos de ar-condicionado</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>0
  – Não tem<br>
    1 – 1 aparelho<br>
    2 – 2 aparelhos<br>
    3 – 3 aparelhos<br>
    4 – 4 aparelhos<br>
    5 – 5 aparelhos<br>
    6 – 6 aparelhos<br>
    7 – 7 aparelhos<br>
    8 – 8 aparelhos<br>
    9 – 9 ou mais aparelhos</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7100</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Numero
  de moradores</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7203</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Densidade
  morador/cômodo</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7204</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Densidade
  morador/dormitorio</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7401</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  1, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7402<span style='mso-spacerun:yes'> </span></td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  2, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7403</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  3, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7404</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  4, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7405</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  5, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7406</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  6, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7407</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  7, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7408</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  8, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7409</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Família
  9, número de componentes</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7616</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  mensal domiciliar</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>V7617</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Rendimento
  domiciliar, salários mínimos</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=116 style='height:15.5pt;border-top:none;
  width:87pt'>P001</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Peso</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>&nbsp;</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V1111</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Existência
  de identificação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não<br>
    9 – Ignorado</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V1112</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Existência
  de iluminação pública</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não<br>
    9 – Ignorado</td>
 </tr>
 <tr height=62 style='height:46.5pt'>
  <td height=62 class=xl66 width=116 style='height:46.5pt;border-top:none;
  width:87pt'>V1113</td>
  <td class=xl66 width=280 style='border-top:none;border-left:none;width:210pt'>Existência
  de calçamento/pavimentação</td>
  <td class=xl67 width=515 style='border-top:none;border-left:none;width:387pt'>1
  – Sim<br>
    2 – Não<br>
    9 – Ignorado</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=116 style='width:87pt'></td>
  <td width=280 style='width:210pt'></td>
  <td width=515 style='width:387pt'></td>
 </tr>
 <![endif]>
</table>



# Families

<table border=0 cellpadding=0 cellspacing=0 width=913 style='border-collapse:
 collapse;table-layout:fixed;width:686pt'>
 <col width=102 style='mso-width-source:userset;mso-width-alt:3560;width:77pt'>
 <col width=278 style='mso-width-source:userset;mso-width-alt:9704;width:209pt'>
 <col width=533 style='mso-width-source:userset;mso-width-alt:18594;width:400pt'>
 <tr height=21 style='height:15.5pt'>
  <td colspan=3 height=21 class=xl69 width=913 style='height:15.5pt;width:686pt'>Variáveis
  do Registro de Familias</td>
 </tr>
 <tr height=27 style='mso-height-source:userset;height:20.5pt'>
  <td height=27 class=xl65 width=102 style='height:20.5pt;border-top:none;
  width:77pt'>Variavel</td>
  <td class=xl65 width=278 style='border-top:none;border-left:none;width:209pt'>Descrição</td>
  <td class=xl65 width=533 style='border-top:none;border-left:none;width:400pt'>Ctegorias</td>
 </tr>
 <tr height=546 style='height:409.5pt'>
  <td height=546 class=xl66 width=102 style='height:409.5pt;border-top:none;
  width:77pt'>V0102</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>UF</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>11-
  Rondônia<br>
    12- Acre<br>
    13- Amazonas<br>
    14- Roraima<br>
    15- Pará<br>
    16- Amapá<br>
    17 - Tocantins<br>
    21- Maranhão<br>
    22- Piauí<br>
    23- Ceará<br>
    24- Rio Grande do Norte<br>
    25- Paraíba<br>
    26- Pernambuco<br>
    27- Alagoas<br>
    28 - Sergipe<br>
    29- Bahia<br>
    31- Minas Gerais<br>
    32- Espírito Santo<br>
    33- Rio de Janeiro<br>
    35- São Paulo<br>
    41- Paraná<br>
    42- Santa Catarina<br>
    43- Rio Grande do Sul<br>
    50- Mato Grosso do Sul<br>
    51- Mato Grosso<br>
    52- Goiás<br>
    53- Distrito Federal</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V1002</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Mesorregião</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V1003</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Microrregião</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V0103</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Município</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V0104</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Distrito</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V0105</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Subdistrito</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V0300</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>controle</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=102 style='height:31.0pt;border-top:none;
  width:77pt'>V0404</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>&gt;00
  (número de ordem da familia no domicilio</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=103 style='height:77.5pt'>
  <td height=103 class=xl66 width=102 style='height:77.5pt;border-top:none;
  width:77pt'>V1001</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Região
  geográfica</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>1-
  Região Norte<br>
    2- Região Nordeste<br>
    3- Região Sudeste<br>
    4- Região Sul<br>
    5- Região Centro-Oeste</td>
 </tr>
 <tr height=546 style='mso-height-source:userset;height:409.5pt'>
  <td height=546 class=xl66 width=102 style='height:409.5pt;border-top:none;
  width:77pt'>V1004</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Regiao
  metropolitana</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  Belém<br>
    02- Grande São Luís<br>
    03- Fortaleza<br>
    04- Natal<br>
    05- Recife<br>
    06- Maceió<br>
    07- Salvador<br>
    08- Belo Horizonte<br>
    09- Colar Metropolitano da RM de Belo Horizonte<br>
    10- Vale do Aço<br>
    11- Colar Metropolitano da RM do Vale do Aço<br>
    12- Grande Vitória<br>
    13- Rio de Janeiro<br>
    14- São Paulo<br>
    15- Baixada Santista<br>
    16- Campinas<br>
    17- Curitiba<br>
    18- Londrina<br>
    19- Maringá<br>
    20- Florianópolis<br>
    21- Área de Expansão Metropolitana da RM de Florianópolis<br>
    22- Núcleo Metropolitano da RM Vale do Itajaí<br>
    23- Área de Expansão Metropolitana da RM Vale do Itajaí<br>
    24- Norte/Nordeste Catarinense<br>
    25- Área de Expansão Metropolitana da RM Norte/Nordeste Catarinense<br>
    26- Porto Alegre<br>
    27– Goiânia<br>
    28– RIDE (Região Integrada de Desenvolvimento do Distrito Federal e
  Entorno)<br>
    Branco- Não aplicável</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl66 width=102 style='height:30.0pt;border-top:none;
  width:77pt'>AREAP</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Area
  de ponderação</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=145 style='height:108.5pt'>
  <td height=145 class=xl66 width=102 style='height:108.5pt;border-top:none;
  width:77pt'>CODV0404</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Tipo
  de família (1)</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>0-
  Única (uma só família vive no domicílio)<br>
    1- Famílias conviventes: 1ª família<br>
    2- Famílias conviventes: 2ª família<br>
    3- Famílias conviventes: 3ª família<br>
    4- Famílias conviventes: 4ª família<br>
    5- Famílias conviventes: 5ª família e mais<br>
    9- Morador individual</td>
 </tr>
 <tr height=248 style='height:186.0pt'>
  <td height=248 class=xl66 width=102 style='height:186.0pt;border-top:none;
  width:77pt'>CODV0404_2</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>tipo
  de família (2)</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  Casal sem filhos<br>
    02- Casal com filhos menores de 14 anos<br>
    03- Casal com filhos de 14 anos ou mais<br>
    04- Casal com filhos de idades variadas<br>
    05- Mãe com filhos menores de 14 anos<br>
    06- Mãe com filhos de 14 anos ou mais<br>
    07- Mãe com filhos de idades variadas<br>
    08- Pai com filhos menores de 14 anos<br>
    09- Pai com filhos de 14 anos ou mais<br>
    10- Pai com filhos de idades variadas<br>
    11- Outros tipos de famílias<br>
    12- Morador individual</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V4614B</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Rendimento
  nominal familiar</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=248 style='height:186.0pt'>
  <td height=248 class=xl66 width=102 style='height:186.0pt;border-top:none;
  width:77pt'>CODV4615B</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de rendimento nominal familiar</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  Até 0,25 salário mínimo<br>
    02- Mais de 0,25 a 0,5 salário mínimo<br>
    03- Mais de 0,5 a 1 salário mínimo<br>
    04- Mais de 1 a 2 salários mínimos<br>
    05- Mais de 2 a 3 salários mínimos<br>
    06- Mais de 3 a 5 salários mínimos<br>
    07- Mais de 5 a 10 salários mínimos<br>
    08- Mais de 10 a 15 salários mínimos<br>
    09- Mais de 15 a 20 salários mínimos<br>
    10- Mais de 20 a 30 salários mínimos<br>
    11- Mais de 30 salários mínimos<br>
    12- Sem rendimento</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V4614C</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Rendimento
  nominal, responsável/casal</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=310 style='height:232.5pt'>
  <td height=310 class=xl66 width=102 style='height:232.5pt;border-top:none;
  width:77pt'>CODV4615C</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de rendimento nominal, responsavel/casal</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  Até 0,25 salário mínimo<br>
    02- Mais de 0,25 a 0,5 salário mínimo<br>
    03- Mais de 0,5 a 0,75 salário mínimo<br>
    04- Mais de 0,75 a 1 salário mínimo<br>
    05- Mais de 1 a 1,25 salários mínimos<br>
    06- Mais de 1,25 a 1,5 salários mínimos<br>
    07- Mais de 1,5 a 2 salários mínimos<br>
    08- Mais de 2 a 3 salários mínimos<br>
    09- Mais de 3 a 5 salários mínimos<br>
    10- Mais de 5 a 10 salários mínimos<br>
    11- Mais de 10 a 15 salários mínimos<br>
    12- Mais de 15 a 20 salários mínimos<br>
    13- Mais de 20 a 30 salários mínimos<br>
    14- Mais de 30 salários mínimos<br>
    15- Sem rendimento</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V4616_7400</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Rendimento
  nominal familiar per-capita</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=248 style='height:186.0pt'>
  <td height=248 class=xl66 width=102 style='height:186.0pt;border-top:none;
  width:77pt'>CODV4615_7400</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de rendimento nominal familiar per-capita</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  Até 0,25 salário mínimo<br>
    02 - Mais de 0,25 a 0,5 salário mínimo<br>
    03- Mais de 0,5 a 1 salário mínimo<br>
    04- Mais de 1 a 2 salários mínimos<br>
    05- Mais de 2 a 3 salários mínimos<br>
    06- Mais de 3 a 5 salários mínimos<br>
    07- Mais de 5 a 10 salários mínimos<br>
    08- Mais de 10 a 15 salários mínimos<br>
    09- Mais de 15 a 20 salários mínimos<br>
    10- Mais de 20 a 30 salários mínimos<br>
    11- Mais de 30 salários mínimos<br>
    12- Sem rendimento</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>V7400</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Numero
  de componentesda familia</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=310 style='height:232.5pt'>
  <td height=310 class=xl66 width=102 style='height:232.5pt;border-top:none;
  width:77pt'>CODV7400</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de numero de componentes</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>01-
  1 pessoa<br>
    02- 2 pessoas<br>
    03- 3 pessoas<br>
    04- 4 pessoas<br>
    05- 5 pessoas<br>
    06- 6 pessoas<br>
    07- 7 pessoas<br>
    08- 8 pessoas<br>
    09- 9 pessoas<br>
    10- 10 pessoas<br>
    11- 11 pessoas<br>
    12- 12 pessoas<br>
    13- 13 pessoas<br>
    14- 14 pessoas<br>
    15- 15 ou mais pessoas</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=102 style='height:31.0pt;border-top:none;
  width:77pt'>V7400A</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Numero
  de componentes homens da familia</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=331 style='height:248.0pt'>
  <td height=331 class=xl66 width=102 style='height:248.0pt;border-top:none;
  width:77pt'>CODV7400A</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de numero de componentes homens</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>00–
  nenhum<br>
    01- 1 homem<br>
    02- 2 homens<br>
    03- 3 homens<br>
    04- 4 homens<br>
    05- 5 homens<br>
    06- 6 homens<br>
    07- 7 homens<br>
    08- 8 homens<br>
    09- 9 homens<br>
    10- 10 homens<br>
    11- 11 homens<br>
    12- 12 homens<br>
    13- 13 homens<br>
    14- 14 homens<br>
    15- 15 ou mais homens</td>
 </tr>
 <tr height=41 style='height:31.0pt'>
  <td height=41 class=xl66 width=102 style='height:31.0pt;border-top:none;
  width:77pt'>V7400B</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Numero
  de componentes mulheres da familia</td>
  <td class=xl68 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=331 style='height:248.0pt'>
  <td height=331 class=xl66 width=102 style='height:248.0pt;border-top:none;
  width:77pt'>CODV7400B</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Classe
  de numero de componentes mulheres</td>
  <td class=xl67 width=533 style='border-top:none;border-left:none;width:400pt'>00–
  nenhuma<br>
    01- 1 mulher<br>
    02- 2 mulheres<br>
    03- 3 mulheres<br>
    04- 4 mulheres<br>
    05- 5 mulheres<br>
    06- 6 mulheres<br>
    07- 7 mulheres<br>
    08- 8 mulheres<br>
    09- 9 mulheres<br>
    10- 10 mulheres<br>
    11- 11 mulheres<br>
    12- 12 mulheres<br>
    13- 13 mulheres<br>
    14- 14 mulheres<br>
    15- 15 ou mais mulheres</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl66 width=102 style='height:15.5pt;border-top:none;
  width:77pt'>P001</td>
  <td class=xl66 width=278 style='border-top:none;border-left:none;width:209pt'>Peso</td>
  <td class=xl68 style='border-top:none;border-left:none'>Peso atribuído ao
  domicílio</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=102 style='width:77pt'></td>
  <td width=278 style='width:209pt'></td>
  <td width=533 style='width:400pt'></td>
 </tr>
 <![endif]>
</table>

